<?php
// $Id: ffcustom.module

/**
 * Implements hook_init().
 */
function ffcustom_init() {
  global $theme_key;
  if (strpos($theme_key, 'bootstrap')===FALSE) {
    require_once(drupal_get_path('theme', 'bootstrap') . '/theme/process.inc');
  }
}

function ffcustom_menu_alter(&$items) {
  // Example - disable the page at node/add
  $items ['node/add/node-gallery-image']['access callback'] = FALSE;
}

function ffcustom_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'department_description' && $view_mode == 'full' && arg(0) == 'node') {

  if (isset($node->field_department['und'][0]['tid'])) {
    $redirect_path = 'taxonomy/term/' . $node->field_department['und'][0]['tid'];
    drupal_goto($redirect_path,array(),301);
    }
  }
}

// Prevent users from changing the department for descriptions
function ffcustom_form_department_description_node_form_alter(&$form, &$form_state, $form_id) {
  $role = user_role_load_by_name('Uber Manager');
  if (!user_has_role($role->rid)) {
    $form['field_department']['#access'] = 0;
  }

}

function ffcustom_form_alter(&$form, &$form_state, $form_id) {
//    if ($form_id == 'event_node_form') {
//      print '<pre>';
//      print($form_id);
//      print_r($form);
//      print '</pre>';
//    }
//  $form['keys_1']['#attributes']['placeholder'] = "Search...";
}

